- name: Install Rust
  when: download_rustup_result.changed
  become_user: "{{ host_user }}"
  block:
    - name: Run Install script
      command: "/home/{{ host_user }}/rustup/install.sh -y"
    - name: Run Rustup override set stable
      shell: "/home/{{ host_user }}/.cargo/bin/rustup override set stable"
      args:
        executable: /bin/bash
    - name: Run Rustup update stable
      shell: "/home/{{ host_user }}/.cargo/bin/rustup update stable"
      args:
        executable: /bin/bash
