- name: Install Bruno
  block:
    - name: Install Bruno using deb
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
      apt:
        deb: https://github.com/usebruno/bruno/releases/download/v1.6.1/bruno_1.6.1_amd64_linux.deb
        state: present
