- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Stop Bluetooth Service
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
      service:
        name: bluetooth.service
        state: stopped
        enabled: no

    - name: Ubuntu Pre-Tasks
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
      block:
        - name: Update Repositories
          apt:
            update_cache: yes
          changed_when: False

        - name: Install Software Properties Common
          apt:
            name: software-properties-common
            state: present

    - name: Arch Pre-Tasks
      when: ansible_distribution in ["Archlinux"]
      block:
        - name: Update Repositories
          pacman:
            update_cache: yes
          changed_when: False

        - name: Install Base Devel
          pacman:
            name: base-devel
            state: present

  roles:
    - { role: disable_locks, tags: disable_locks }
    - { role: alacritty, tags: alacritty }
    - { role: bat, tags: bat }
    - { role: brave, tags: brave }
    - { role: bruno, tags: bruno }
    - { role: bun, tags: bun }
    - { role: cron, tags: cron }
    - { role: delta, tags: delta }
    - { role: discord, tags: discord }
    - { role: docker, tags: docker }
    - { role: flatpak, tags: flatpak }
    - { role: fonts, tags: fonts }
    - { role: gnome_tweaks, tags: gnome_tweaks }
    - { role: go, tags: go }
    - { role: gum, tags: gum }
    - { role: lutris, tags: lutris }
    - { role: musikcube, tags: musikcube }
    - { role: neovim, tags: neovim }
    - { role: node, tags: node }
    - { role: nvm, tags: nvm }
    - { role: obsidian, tags: obsidian }
    - { role: oh_my_bash, tags: oh_my_bash }
    - { role: packages, tags: packages }
    - { role: paru, tags: paru }
    - { role: psutil, tags: psutil }
    - { role: python, tags: python }
    - { role: rust, tags: rust }
    - { role: rustup, tags: rustup }
    - { role: ssh, tags: ssh }
    - { role: stremio, tags: stremio }
    - { role: syncthing, tags: syncthing }
    - { role: telegram, tags: telegram }
    - { role: test_shell, tags: test_shell }
    - { role: users, tags: users }
    - { role: vi, tags: vi }
    - { role: vlc, tags: vlc }
    - { role: whatsapp, tags: whatsapp }
    - { role: zellij, tags: zellij }
    - { role: zjstatus, tags: zjstatus }
    - { role: dotfiles, tags: dotfiles }
