- name: Ensure Neofetch Config Directory Exists
  become_user: "{{ host_user }}"
  file:
    path: "/home/{{ host_user }}/.config/neofetch/"
    state: directory
    mode: 0755

- name: Create Symbolic Link for Bat command
  become_user: "{{ host_user }}"
  block:
    - name: Ensure Local Bin Directory Exists
      file:
        path: "/home/{{ host_user }}/.local/bin/"
        state: directory
        mode: 0755
    - name: Make Symbolic Link
      file:
        src: /usr/bin/batcat
        dest: "/home/{{ host_user }}/.local/bin/bat"
        state: link
        mode: 0755

- name: Install Delta
  become_user: "{{ host_user }}"
  command: "/home/{{ host_user }}/.cargo/bin/cargo install git-delta"

- name: Install Zellij
  become_user: "{{ host_user }}"
  command: "/home/{{ host_user }}/.cargo/bin/cargo install --locked zellij"

- name: Install Zjstatus Plugin for Zellij
  become_user: "{{ host_user }}"
  block:
    - name: Add Wasm32-Wasi Target to Rustup
      command: "rustup target add wasm32-wasi"
    - name: Clone Zjstatus Repository
      git:
        dest: "/home/{{ host_user }}/zjstatus/"
        recursive: no
        repo: "https://github.com/dj95/zjstatus.git"
    - name: Build zjstatus from source
      command:
        chdir: "/home/{{ host_user }}/zjstatus/"
        cmd: "cargo build --release"
