- name: Install packages
  block:
    - name: PopOS Packages
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
      apt:
        name:
          - build-essential
          - libssl-dev
          - libgtk-3-dev
          - libgtk-4-dev
          - libayatana-appindicator3-dev
          - librsvg2-dev
          - git-all
          - btop
          - exa
          - pass
          - kdeconnect

    - name: Arch Packages
      when: ansible_distribution in ["Archlinux"]
      pacman:
        name:
          - openssl
          - gtk3
          - gtk-layer-shell
          - libappindicator-gtk3
          - librsvg
          - btop
          - exa
          - pass
          - kdeconnect
          - brightnessctl
          - playerctl
          - kwallet-pam
          - jq
          - gtk4
