- name: Setup cronjob for auto update ansible script
  block:
    - name: Install Cronjob
      cron:
        user: ansible
        name: "Ansible Provision"
        minute: 0
        hour: 0
        state: present
        job: '/usr/bin/ansible-pull -o -U https://github.com/brimmar/dotfiles.git -e "host_user={{ host_user }}" > /dev/null'
