- name: Install Python
  block:
    - name: Install Python
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
      apt:
        name:
          - python3
          - python3-dev
          - python3-pip
