- name: Install paru
  when: ansible_distribution in ["Archlinux"]
  become_user: "{{ host_user }}"
  block:
    - name: Clone paru repository
      git:
        dest: "/home/{{ host_user }}/paru/"
        recursive: no
        repo: "https://aur.archlinux.org/paru.git"

    - name: Give permission
      file:
        path: "/home/{{ host_user }}/paru"
        state: directory
        owner: "{{ host_user }}"
        mode: 0755

    - name: Run makepkg
      command:
        chdir: "/home/{{ host_user }}/paru/"
        cmd: makepkg -si --noconfirm
