- name: Install Musikcube
  block:
    - name: Install Musikcube using deb
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
      apt:
        deb: https://github.com/clangen/musikcube/releases/download/3.0.2/musikcube_3.0.2_linux_x86_64.deb
        state: present
