- name: Install Zjstatus Plugin for Zellij
  become_user: "{{ host_user }}"
  block:
    - name: Ensure Zjstatus is not already installed
      stat:
        path: "/home/{{ host_user }}/zjstatus/"
      register: zjstatus_status
    - name: Clone Zjstatus Repository
      when: not zjstatus_status.stat.exists
      git:
        dest: "/home/{{ host_user }}/zjstatus/"
        recursive: no
        repo: "https://github.com/brimmar/zjstatus.git"
    - name: Add Wasm32-Wasi Target to Rustup
      command:
        chdir: "/home/{{ host_user }}/zjstatus/"
        cmd: "/home/{{ host_user }}/.cargo/bin/rustup target add wasm32-wasi"
    - name: Build zjstatus from source
      command:
        chdir: "/home/{{ host_user }}/zjstatus/"
        cmd: "/home/{{ host_user }}/.cargo/bin/cargo build --release --target wasm32-wasi"
