- name: Download Rustup
  become_user: "{{ host_user }}"
  block:
    - name: Log Rust installation starts
      lineinfile:
        path: "{{ log_file }}"
        line: "{{ ansible_date_time.iso8601 }} - Starting Rust installation"
      ignore_errors: true

    - name: Ensure Rust Directory Exists
      file:
        path: "/home/{{ host_user }}/rustup/"
        state: directory
        mode: 0755

    - name: Download Rustup
      get_url:
        url: https://sh.rustup.rs
        dest: "/home/{{ host_user }}/rustup/install.sh"
        mode: 0755
      register: download_rustup_result
      until: download_rustup_result is success
      retries: 3
      delay: 5
