- name: Install Gum
  block:
    - name: Install Gum
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
      block:
        - name: Download Gum Binary
          apt:
            deb: https://github.com/charmbracelet/gum/releases/download/v0.13.0/gum_0.13.0_amd64.deb
            state: present
