- name: Ensures SSH Key Does not Exists
  stat:
    path: "/home/{{ host_user }}/.ssh/id_ed25519"
  register: ssh_status

- name: Create SSH Key
  when: ssh_status.stat.exists == false
  become_user: "{{ host_user }}"
  command: ssh-keygen -t ed25519 -C "{{ ssh_email }}" -q -N "" -f "/home/{{ host_user }}/.ssh/id_ed25519"

- name: Ensure Nerd Font Directory does not Exists
  stat:
    path: "/home/{{ host_user }}/nerd-fonts/"
  register: nerdfonts_status

- name: Download Nerd Fonts
  become_user: "{{ host_user }}"
  when: nerdfonts_status.stat.exists == false
  command:
    chdir: "/home/{{ host_user }}"
    cmd: git clone --filter=blob:none --sparse https://github.com/ryanoasis/nerd-fonts
  register: download_nerdfonts_result

- name: Install Nerd Fonts
  when: download_nerdfonts_result.changed
  become_user: "{{ host_user }}"
  shell:
    chdir: "/home/{{ host_user }}/nerd-fonts/"
    cmd: git sparse-checkout add patched-fonts/Hack && ./install.sh -s

- name: Stop Bluetooth Service
  when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
  service:
    name: bluetooth.service
    state: stopped
    enabled: no

# TODO: Arrumar isso aqui depois, dar um jeito de não precisar de copiar e fazer o symlink
- name: Git Clone Dotfiles
  become_user: "{{ host_user }}"
  block:
    - name: Ensure Dotfiles directory do not exists
      file:
        path: "/home/{{ host_user }}/dotfiles"
        state: absent
    - name: Git Clone
      command:
        chdir: "/home/{{ host_user }}"
        cmd: git clone -n --depth=1 --filter=tree:0 https://github.com/brimmar/dotfiles.git
    - name: Git Sparse Checkout
      shell:
        chdir: "/home/{{ host_user }}/dotfiles/"
        cmd: git sparse-checkout set --no-cone dotfiles
    - name: Git Checkout
      shell:
        chdir: "/home/{{ host_user }}/dotfiles/"
        cmd: git checkout

- name: Create Symlinks to config files
  become_user: "{{ host_user }}"
  block:
    - name: Symlink nvim
      file:
        src: "/home/{{ host_user }}/dotfiles/dotfiles/nvim/.config/nvim"
        dest: "/home/{{ host_user }}/.config/nvim"
        state: link
        force: yes
        mode: 0755
    - name: Symlink neofetch
      file:
        src: "/home/{{ host_user }}/dotfiles/dotfiles/neofetch/.config/neofetch"
        dest: "/home/{{ host_user }}/.config/neofetch"
        state: link
        force: yes
        mode: 0755
    - name: Symlink gitconfig
      file:
        src: "/home/{{ host_user }}/dotfiles/dotfiles/gitconfig/.gitconfig"
        dest: "/home/{{ host_user }}/.gitconfig"
        state: link
        force: yes
        mode: 0755
    - name: Symlink alacritty
      file:
        src: "/home/{{ host_user }}/dotfiles/dotfiles/alacritty/.config/alacritty"
        dest: "/home/{{ host_user }}/.config/alacritty"
        state: link
        force: yes
        mode: 0755
    - name: Symlink bashrc
      file:
        src: "/home/{{ host_user }}/dotfiles/dotfiles/oh-my-bash/.bashrc"
        dest: "/home/{{ host_user }}/.bashrc"
        state: link
        force: yes
        mode: 0755
    - name: Symlink Oh-My-Bash
      file:
        src: "/home/{{ host_user }}/dotfiles/dotfiles/oh-my-bash/.oh-my-bash/themes/sexy/sexy.theme.sh"
        dest: "/home/{{ host_user }}/.oh-my-bash/themes/sexy/sexy.theme.sh"
        state: link
        force: yes
        mode: 0755
    - name: Symlink Zellij
      file:
        src: "/home/{{ host_user }}/dotfiles/dotfiles/zellij/.config/zellij"
        dest: "/home/{{ host_user }}/.config/zellij"
        state: link
        force: yes
        mode: 0755
    - name: Symlink Hypr
      when: ansible_distribution in ["Archlinux"]
      block:
        - name: Ensure Hypr Directory do not exist
          file:
            path: "/home/{{ host_user }}/.config/hypr"
            state: absent
        - name: Symlink Hypr
          file:
            src: "/home/{{ host_user }}/dotfiles/dotfiles/hypr/.config/hypr"
            dest: "/home/{{ host_user }}/.config/hypr"
            state: link
            force: yes
            mode: 0755

- name: Configure Desktop Environment
  when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
  become_user: "{{ host_user }}"
  block:
    - name: Background
      block:
        - name: Color Shading Type
          dconf:
            key: "/org/gnome/desktop/background/color-shading-type"
            value: "'solid'"
            state: present
        - name: Picture Options
          dconf:
            key: "/org/gnome/desktop/background/picture-options"
            value: "'zoom'"
            state: present
        - name: Picture Uri Dark
          dconf:
            key: "/org/gnome/desktop/background/picture-uri-dark"
            value: "'file:///usr/share/backgrounds/pop/nick-nazzaro-space-blue.png'"
            state: present
        - name: Primary Color
          dconf:
            key: "/org/gnome/desktop/background/primary-color"
            value: "'#000000'"
            state: present
        - name: Secondary Color
          dconf:
            key: "/org/gnome/desktop/background/secondary-color"
            value: "'#000000'"
            state: present
    - name: Interface
      block:
        - name: Clock Format
          dconf:
            key: "/org/gnome/desktop/interface/clock-format"
            value: "'24h'"
            state: present
        - name: Color Scheme
          dconf:
            key: "/org/gnome/desktop/interface/color-scheme"
            value: "'prefer-dark'"
            state: present
        - name: Animations
          dconf:
            key: "/org/gnome/desktop/interface/enable-animations"
            value: "false"
            state: present
        - name: Font Antialiasing
          dconf:
            key: "/org/gnome/desktop/interface/font-antialiasing"
            value: "'grayscale'"
            state: present
        - name: Font Hinting
          dconf:
            key: "/org/gnome/desktop/interface/font-hinting"
            value: "'slight'"
            state: present
    - name: Mouse
      block:
        - name: Speed
          dconf:
            key: "/org/gnome/desktop/peripherals/mouse/speed"
            value: "-0.34558823529411764"
            state: present
    - name: Touchpad
      block:
        - name: Touchpad Events
          dconf:
            key: "/org/gnome/desktop/peripherals/touchpad/send-events"
            value: "'enabled'"
            state: present
        - name: Two Finger Scrolling
          dconf:
            key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled"
            value: "true"
            state: present
    - name: Preferences
      block:
        - name: Button Layout
          dconf:
            key: "/org/gnome/desktop/wm/preferences/button-layout"
            value: "'appmenu:close'"
            state: present
        - name: Number of Workspaces
          dconf:
            key: "/org/gnome/desktop/wm/preferences/num-workspaces"
            value: "6"
            state: present
    - name: Mutter
      block:
        - name: Dynamic Workspaces
          dconf:
            key: "/org/gnome/mutter/dynamic-workspaces"
            value: "false"
            state: present
        - name: Edge Tiling
          dconf:
            key: "/org/gnome/mutter/edge-tiling"
            value: "false"
            state: present
        - name: Workspaces Only on Primary
          dconf:
            key: "/org/gnome/mutter/workspaces-only-on-primary"
            value: "true"
            state: present
    - name: Power
      block:
        - name: Sleep AC Timeout
          dconf:
            key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout"
            value: "1800"
            state: present
        - name: Sleep AC Type
          dconf:
            key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
            value: "'nothing'"
            state: present
        - name: Sleep Battery Timeout
          dconf:
            key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout"
            value: "1800"
            state: present
        - name: Sleep Battery Type
          dconf:
            key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type"
            value: "'suspend'"
    - name: Dash to Dock
      block:
        - name: Extend Height
          dconf:
            key: "/org/gnome/shell/extensions/dash-to-dock/extend-height"
            value: "false"
            state: present
        - name: Manual Hide
          dconf:
            key: "/org/gnome/shell/extensions/dash-to-dock/manualhide"
            value: "true"
            state: present
    - name: Pop Cosmic
      block:
        - name: Clock alignment
          dconf:
            key: "/org/gnome/shell/extensions/pop-cosmic/clock-alignment"
            value: "'RIGHT'"
            state: present
        - name: Show Applications
          dconf:
            key: "/org/gnome/shell/extensions/pop-cosmic/show-applications-button"
            value: "false"
            state: present
        - name: Show Workspaces
          dconf:
            key: "/org/gnome/shell/extensions/pop-cosmic/show-workspaces-button"
            value: "false"
            state: present
    - name: Pop Shell
      block:
        - name: Active Hint
          dconf:
            key: "/org/gnome/shell/extensions/pop-shell/active-hint"
            value: "true"
            state: present
        - name: Active Hint Border Radius
          dconf:
            key: "/org/gnome/shell/extensions/pop-shell/active-hint-border-radius"
            value: "uint32 0"
            state: present
        - name: Inner Gap
          dconf:
            key: "/org/gnome/shell/extensions/pop-shell/gap-inner"
            value: "uint32 0"
            state: present
        - name: Outer Gap
          dconf:
            key: "/org/gnome/shell/extensions/pop-shell/gap-outer"
            value: "uint32 0"
            state: present
        - name: Hint Color RGBA
          dconf:
            key: "/org/gnome/shell/extensions/pop-shell/hint-color-rgba"
            value: "'rgb(102, 102, 102)'"
            state: present
        - name: Show Title
          dconf:
            key: "/org/gnome/shell/pop-shell/show-title"
            value: "false"
            state: present
        - name: Title By Default
          dconf:
            key: "/org/gnome/shell/pop-shell/title-by-default"
            value: "true"
            state: present
    - name: Location
      block:
        - name: Enable
          dconf:
            key: "/org/gnome/system/location/enabled"
            value: "false"
            state: present
