- name: Install Docker
  block:
    - name: Add Docker Repository
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
      block:
        - name: Add Docker Keyring
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker Repository
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
            state: present

    - name: Download Docker
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
      apt:
        name:
          - docker-ce
      register: download_docker_status
    - name: Download Docker
      when: ansible_distribution in ["Archlinux"]
      pacman:
        name:
          - docker
      register: download_docker_status

    - name: Start Docker Service
      when: ansible_distribution in ["Archlinux"]
      service:
        name: "docker"
        enabled: yes
        state: started

    - name: Add Docker User
      when: download_docker_status.changed
      command: "usermod -aG docker {{ host_user }}"

    - name: Update Docker Groups
      become_user: "{{ host_user }}"
      when: download_docker_status.changed
      command: newgrp docker
