- name: Install Syncthing
  block:
    - name: Install Syncthing
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
      block:
        - name: Add Syncthing Repository
          block:
            - name: Download Syncthing GPG key
              get_url:
                url: https://syncthing.net/release-key.txt
                dest: /usr/share/keyrings/syncthing-archive-keyring.gpg
                mode: '0644'

            - name: Add Syncthing Repository
              apt_repository:
                repo: "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"
                state: present
                filename: syncthing

        - name: Install APT Syncthing Package
          apt:
            name: syncthing

    - name: Enable syncthing service
      service:
        name: "syncthing@{{ host_user }}.service"
        enabled: yes
        state: started
